<?php

return [
    // 'Sid'  =>  '用户id',
    // 'License'  =>  '公司认证编号',
    // 'Openid'  => '微信关联id',
    'muid'  =>  '创建人uid',
    'name'  =>  '员工名字',
    'picpath'  =>  '员工证件照存放地址',
    'addtime'  =>  '首次添加时间',
    'uptime'  =>  '最近一次更新资料时间',
    'birthday'  =>  '员工生日',
    'jointime'  =>  '入职时间',
    'gender'  =>  '性别(0:男,1:女)',
    'counts'  =>  '此员工所拥有的图片张数',
    'position'  =>  '职位',
    'phone'  =>  '手机',
    'Email' => '邮箱',
    'address'  =>  '住址',
    'staff_type'  =>  '判断是否访客(0:员工,1访客,3vip)',
    'guesttime'  =>  '访客生效时间（也可以作为访客到访时间）',
    'expiration'  =>  '访客过期时间',
    'guest_status'  =>  '过期访客是否处理完(0未处理,1已处理,2处理失败)',
    'cor_depart'  =>  '部门/公司',
    'get_status'  =>  '标示此员工的记录是否被客户获取0未,1已获取',
    'add_way'  =>  '员工添加方式0微信,1本地客户端同步',
    'update_status'  =>  '0默认,1更新资料,2更新资料+face图片',
    'followed'  =>  '0已关注,1已经取消关注',
    'phone_guest'  =>  '该人员是否由手机端添加(0不是,1是)'
];
